global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "dineflow-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # DineFlow application metrics
  - job_name: 'dineflow'
    static_configs:
      - targets: ['dineflow:3000']
    metrics_path: '/monitoring/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Node.js application metrics
  - job_name: 'nodejs'
    static_configs:
      - targets: ['dineflow:3000']
    metrics_path: '/monitoring/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # MongoDB metrics (if using mongodb-exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics (if using redis-exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics (if using nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics (if using node-exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker metrics (if using cadvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s 